//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProduccion.Entities.ModulosSistemas
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolesoperaciones
    {
        public int id { get; set; }
        public int Rol_Id { get; set; }
        public int Operaciones_Id { get; set; }
    
        public virtual operaciones operaciones { get; set; }
        public virtual rol rol { get; set; }
    }
}
