//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProduccion.Entities.ModulosEscaneos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A3F19C_producccionEntities : DbContext
    {
        public DB_A3F19C_producccionEntities()
            : base("name=DB_A3F19C_producccionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<li_cajas> li_cajas { get; set; }
        public virtual DbSet<li_detcajasskus> li_detcajasskus { get; set; }
        public virtual DbSet<li_origen> li_origen { get; set; }
        public virtual DbSet<li_status> li_status { get; set; }
        public virtual DbSet<li_statustarimas> li_statustarimas { get; set; }
        public virtual DbSet<li_tarimas> li_tarimas { get; set; }
        public virtual DbSet<logisticainversa> logisticainversa { get; set; }
        public virtual DbSet<skus> skus { get; set; }
        public virtual DbSet<skusbenavides> skusbenavides { get; set; }
        public virtual DbSet<skusinventarios> skusinventarios { get; set; }
        public virtual DbSet<uom> uom { get; set; }
        public virtual DbSet<wl_detcajassku> wl_detcajassku { get; set; }
        public virtual DbSet<wl_tiendas> wl_tiendas { get; set; }
        public virtual DbSet<wl_guias> wl_guias { get; set; }
        public virtual DbSet<wl_statuscajas> wl_statuscajas { get; set; }
        public virtual DbSet<wl_detenvios> wl_detenvios { get; set; }
        public virtual DbSet<wl_waldos> wl_waldos { get; set; }
        public virtual DbSet<auditores> auditores { get; set; }
        public virtual DbSet<pickers> pickers { get; set; }
        public virtual DbSet<kits> kits { get; set; }
        public virtual DbSet<kitskus> kitskus { get; set; }
        public virtual DbSet<wl_cajas> wl_cajas { get; set; }
    }
}
