//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppProduccion.Entities.ModulosAdministracion
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactosproveedores
    {
        public int id { get; set; }
        public string Nombres { get; set; }
        public string Email { get; set; }
        public string Puesto { get; set; }
        public int Proveedores_Id { get; set; }
        public string Telefono { get; set; }
    
        public virtual proveedores proveedores { get; set; }
    }
}
